# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bisMateClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bisMateClient
  pod 'Firebase/Auth'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Starscream', '~> 4.0.0'

  target 'bisMateClientTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Auth'
  end

  target 'bisMateClientUITests' do
    # Pods for testing
  end

end
