name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Install dependencies
      run: |
        cd Server/src && go version
        cd Server/src && go mod init
        cd Server/src && go mod tidy
        cd Server/src && go mod download cloud.google.com/go/firestore
        cd Server/src && go get firebase.google.com/go
        cd Server/src && go get firebase.google.com/go/auth
        cd Server/src && go get google.golang.org/api/option

    - name: Test
      run: cd Server/src && go test -v ./...
