name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Install dependencies
      run: |
        go version
        go get firebase.google.com/go

    - name: Build
      run: cd Server/src && go test -v ./...

    - name: Test
      run: cd Server/src && go test -v ./...
