name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Install dependencies
      run: |
        go version
        go mod tidy
        cd Server/src/firebase && go mod init fbadmin_test
        go mod download cloud.google.com/go/firestore
        go get firebase.google.com/go
        go get firebase.google.com/go/auth
        go get google.golang.org/api/option

    - name: Test
      run: cd Server/src && go test -v ./...
